#! /bin/bash

export COOKIE='Cookie: id=saksham0808; timestamp=1430940663; auth=D546C5E71058DF8BDEF97D94CD8831D1E4598109'

http post localhost:7771/ed4j id="hackcave" name="Hack Cave" properties:='{}' $COOKIE
